var mongoose=require('mongoose');
var userSchema=new mongoose.Schema({
   "userId":String,
   "userName":String,
   "userPwd":String,
   "orderList":[
     {
      "orderId":String,
      "orderTotal":Number,
      "addressInfo":[{
          "addressId":String,
          "userName":String,
          "streetName":String,
          "postCode":String,
          "tel":String,
          "isDefault":Boolean
       }],
      "goodsList":[{
         "productId":String,
         "productName":String,
         "salePrice":Number,
         "productImage":String,
         "checked":String,
         "productNum":Number
      }],
      "orderStatus":String,
      "createDate":Date
     }
    ],
   "cartList":[
      {
       "productId":String,
       "productName":String,
       "salePrice":Number,
       "productImage":String,
       "checked":String,
       "productNum":Number
      } 
   ],
   "addressList":[
      {
        "addressId":String,
        "userName":String,
        "streetName":String,
        "postCode":String,
        "tel":String,
        "isDefault":Boolean
      }
   ]
});

module.exports=mongoose.model("User",userSchema);